name: gmsc_mapper_test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Install dependencies
      run: |
        pip install pytest
        pip install atomicwrites
        pip install pyrodigal
        pip install pandas
        pip install biopython
        wget https://mmseqs.com/latest/mmseqs-linux-avx2.tar.gz -P ./bin
        tar xvfz ./bin/mmseqs-linux-avx2.tar.gz
        wget http://github.com/bbuchfink/diamond/releases/download/v2.1.8/diamond-linux64.tar.gz -P ./bin
        tar xzf ./bin/diamond-linux64.tar.gz
        python ./setup.py install
    - name: Test with pytest
      run: |
        python -m pytest ./tests
